# Generated by Django 3.1.4 on 2021-02-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orders',
            name='total_price',
            field=models.CharField(default='', max_length=50),
        ),
    ]
